#!/usr/bin/env python3
"""Generate kleis's built-in Matrix glyph alpha source from CNTR KoineGreek."""

from __future__ import annotations

import argparse
from pathlib import Path

from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FONT = ROOT / "third_party" / "cntr-font" / "KoineGreek.ttf"
DEFAULT_OUT = ROOT / "src" / "kleis" / "font64x128.nim"

GLYPHS = [
    "\u03b1", "\u03b2", "\u03b3", "\u03b4", "\u03b5", "\u03b6",
    "\u03b7", "\u03b8", "\u03b9", "\u03ba", "\u03bb", "\u03bc",
    "\u03bd", "\u03be", "\u03bf", "\u03c0", "\u03c1", "\u03c3",
    "\u03c2", "\u03c4", "\u03c5", "\u03c6", "\u03c7", "\u03c8",
    "\u03c9", "\u03f2", "\u03db", "\u03df", "\u03d7", "\u2ce8",
    "\ue000", "\ue001", "\u0375", "\u0305",
]

WIDTH = 64
HEIGHT = 64
OVERSAMPLE = 4
FONT_SIZE = 66


def font_cmap(path: Path) -> dict[int, str]:
    font = TTFont(path)
    cmap: dict[int, str] = {}
    for table in font["cmap"].tables:
        cmap.update(table.cmap)
    return cmap


def render_glyph(font: ImageFont.FreeTypeFont, glyph: str) -> list[int]:
    canvas_w = WIDTH * OVERSAMPLE
    canvas_h = HEIGHT * OVERSAMPLE
    scratch = Image.new("L", (canvas_w * 2, canvas_h * 2), 0)
    draw = ImageDraw.Draw(scratch)
    bbox = draw.textbbox((0, 0), glyph, font=font)
    x = scratch.width // 2 - (bbox[2] - bbox[0]) // 2 - bbox[0]
    y = scratch.height // 2 - (bbox[3] - bbox[1]) // 2 - bbox[1]
    draw.text((x, y), glyph, font=font, fill=255)

    alpha_bbox = scratch.getbbox()
    if alpha_bbox is None:
        raise ValueError(f"glyph U+{ord(glyph):04X} rendered blank")

    crop = scratch.crop(alpha_bbox)
    if crop.width > canvas_w or crop.height > canvas_h:
        raise ValueError(
            f"glyph U+{ord(glyph):04X} rendered too large: "
            f"{crop.width}x{crop.height}, max {canvas_w}x{canvas_h}"
        )

    glyph_img = Image.new("L", (canvas_w, canvas_h), 0)
    glyph_img.paste(crop, ((canvas_w - crop.width) // 2, (canvas_h - crop.height) // 2))
    glyph_img = glyph_img.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    return list(glyph_img.tobytes())


def rle(values: list[int]) -> list[tuple[int, int]]:
    runs: list[tuple[int, int]] = []
    if not values:
        return runs
    count = 1
    current = values[0]
    for value in values[1:]:
        if value == current and count < 65535:
            count += 1
            continue
        runs.append((count, current))
        current = value
        count = 1
    runs.append((count, current))
    return runs


def nim_rle_literal(runs: list[tuple[int, int]]) -> str:
    chunks = [f"({count}'u16, {value}'u8)" for count, value in runs]
    lines = []
    for idx in range(0, len(chunks), 4):
        lines.append("    " + ", ".join(chunks[idx:idx + 4]))
    return ",\n".join(lines)


def generate(font_path: Path, out_path: Path) -> None:
    cmap = font_cmap(font_path)
    missing = [glyph for glyph in GLYPHS if ord(glyph) not in cmap]
    if missing:
        names = ", ".join(f"U+{ord(glyph):04X}" for glyph in missing)
        raise ValueError(f"font is missing required glyphs: {names}")

    font = ImageFont.truetype(str(font_path), FONT_SIZE * OVERSAMPLE)
    pixels: list[int] = []
    for glyph in GLYPHS:
        pixels.extend(render_glyph(font, glyph))

    runs = rle(pixels)
    body = f"""\
# Generated by scripts/generate-cntr-font.py from third_party/cntr-font/KoineGreek.ttf.
# Do not edit by hand.
#
# KoineGreek.ttf is copyright 2012-2023 Alan Bunning / Center for New
# Testament Restoration and is distributed under CC BY-SA 4.0. The generated
# glyph alpha data below is derived from that font and is distributed under the
# same license terms. kleis source code remains MIT-licensed.

const
  HighResGlyphWidth* = {WIDTH}
  HighResGlyphHeight* = {HEIGHT}
  KoineGlyphCount* = {len(GLYPHS)}
  KoineFontRleLen = {len(runs)}

type
  HighResGlyph* = array[HighResGlyphWidth * HighResGlyphHeight, uint8]
  HighResFont* = array[KoineGlyphCount, HighResGlyph]
  GlyphRun = tuple[count: uint16, value: uint8]

const KoineFontRle: array[KoineFontRleLen, GlyphRun] = [
{nim_rle_literal(runs)}
]

proc decodeHighResFont(): HighResFont =
  var glyphIdx = 0
  var pixelIdx = 0
  for run in KoineFontRle:
    for _ in 0 ..< int(run.count):
      doAssert glyphIdx < KoineGlyphCount
      result[glyphIdx][pixelIdx] = run.value
      inc pixelIdx
      if pixelIdx == HighResGlyphWidth * HighResGlyphHeight:
        pixelIdx = 0
        inc glyphIdx
  doAssert glyphIdx == KoineGlyphCount
  doAssert pixelIdx == 0

let KoineHighResFont* = decodeHighResFont()
"""
    out_path.write_text(body, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    generate(args.font, args.out)


if __name__ == "__main__":
    main()
